ignore: False
active_stages:
stages:
  - name: "stage 1"
    auto_approve: False
    targets:
      - module:
          - vpc
          - subnet
          - vm-1
  - name: "stage 2"
    auto_approve: False
    targets:
      - module:
          - vm-2
