name: Get github commit details
on:
    push:
        # tags:
        #     - "platform/*/userid/*/terraformx/*/dir/*/v/*"

jobs:
    get_github_details:
        runs-on: ubuntu-latest
        steps:
            - name: Get tag annotation and retrieve secrets
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              id: tagger
              run: |
                  gh api --header 'Accept: application/vnd.github+json' --header 'X-GitHub-Api-Version:2022-11-28' --method GET /octocat
              shell: bash
