name: Get github commit details
on:
  push:
    tags:
      - "v*"

jobs:
  get_github_details:
    runs-on: ubuntu-latest
    env:
      message: ${{ github.event.head_commit.message }}
      actor: ${{ github.actor }}
      actactor_idor: ${{ github.actor_id }}
    steps:
      - name: Echo env
        run: |
          echo "\nmessage: $message"
          echo "\nactor: $actor"
          echo "\nactor_id: $actor_id"
        shell: bash
