name: Get github commit details
on:
  push:
    # tags:
    #   - "v*"

jobs:
  get_github_details:
    runs-on: ubuntu-latest
    steps:
      - name: Get tagger block from tag annotations
        id: tagger
        run: |
          echo "Tag: ${GITHUB_REF##*/}"

          # tag_response=$(curl "https://api.github.com/repos/jlieow/hello-github-api/git/refs/tags/${GITHUB_REF##*/}" \
          tag_response=$(curl "https://api.github.com/repos/jlieow/hello-github-api/git/refs/tags/v0.0.25" \
          -H "Accept: application/json" \
          -H "Content-Type:application/json")

          echo "tag_response: $tag_response"

          url=$(echo $tag_response | jq -r '.object | "\(.url)"')

          echo "url: $url"

          tag_annotations=$(curl "$url" \
          -H "Accept: application/json" \
          -H "Content-Type:application/json")

          tagger_response=$(echo $tag_annotations | jq -r '.tagger')

          echo "tagger_response: $tagger_response"

          echo $tagger_response | jq --arg key message -r '.[$key]'
        shell: bash

      # - name: Get output from
      #   run: |
      #     echo "tagger is ${{ steps.tagger.outputs.tagger_response }}"
      #   shell: bash

      - name: Get secrets
        run: |
          echo "secrets: ${{ toJson(secrets) }}"

          secrets=$(cat <<EOF
          ${{ toJson(secrets) }}
          EOF
          )

          secret_name=U041VQM5ZTK_AWS_PROFILE_NAME

          echo "secret_name = $secret_name"

          echo $secrets | jq --arg key $secret_name -r '.[$key]'
        shell: bash
