name: Get github commit details
on:
  push:
    tags:
      - "v*"

jobs:
  get_github_details:
    runs-on: ubuntu-latest
    steps:
      - name: Echo env
        run: |
          echo "Works. Tag is ${GITHUB_REF##*/}"

          tag_ref=${GITHUB_REF##*/}
          
          tag=$(curl "https://api.github.com/repos/jlieow/hello-github-api/git/refs/tags/${GITHUB_REF##*/}" \
          -H "Accept: application/json" \
          -H "Content-Type:application/json")

          echo "Tag: $tag"

          url=$(echo $tag | jq -r '.object | "\(.url)"') 

          echo "url: $url"

          echo $tag | jq -r '.object | "\(.url)"' | while read url ; do
            echo "dddd: $url"
          done
        shell: bash
