name: Get github commit details
on:
  push:
    tags:
      - "v*"

jobs:
  get_github_details:
    runs-on: ubuntu-latest
    steps:
      - name: Get tagger block from tag annotations
        run: |
          echo "Tag: ${GITHUB_REF##*/}"
          
          tag_response=$(curl "https://api.github.com/repos/jlieow/hello-github-api/git/refs/tags/${GITHUB_REF##*/}" \
          -H "Accept: application/json" \
          -H "Content-Type:application/json")

          echo "tag_response: $tag_response"

          url=$(echo $tag_response | jq -r '.object | "\(.url)"') 

          echo "url: $url"

          tag_annotations=$(curl "$url" \
          -H "Accept: application/json" \
          -H "Content-Type:application/json")

          tagger_response=$(echo $tag_annotations | jq -r '.tagger') 

          echo "tagger_response: $tagger_response"
        shell: bash
