name: Get github commit details
on:
  push:
    # tags:
    #   - "v*"

jobs:
  get_github_details:
    runs-on: ubuntu-latest
    steps:
      # - name: Get tagger block from tag annotations
      #   id: tagger
      #   run: |
      #     echo "Tag: ${GITHUB_REF##*/}"

      #     tag_response=$(curl "https://api.github.com/repos/jlieow/hello-github-api/git/refs/tags/${GITHUB_REF##*/}" \
      #     -H "Accept: application/json" \
      #     -H "Content-Type:application/json")

      #     echo "tag_response: $tag_response"

      #     url=$(echo $tag_response | jq -r '.object | "\(.url)"')

      #     echo "url: $url"

      #     tag_annotations=$(curl "$url" \
      #     -H "Accept: application/json" \
      #     -H "Content-Type:application/json")

      #     tagger_response=$(echo $tag_annotations | jq -r '.tagger')

      #     echo "tagger_response: $tagger_response"

      #     # echo "tagger_response=$tagger_response" >> $GITHUB_OUTPUT
      #     echo 'var<<EOF' >> $GITHUB_OUTPUT
      #     echo "tagger_response=test_tagger_response" >> $GITHUB_OUTPUT
      #     echo 'EOF' >> $GITHUB_OUTPUT
      #   shell: bash

      # - name: Get output from
      #   run: |
      #     echo "tagger is ${{ steps.tagger.outputs.tagger_response }}"
      #   shell: bash

      - name: Get secrets
        run: |
          echo "secrets: ${{ toJson(secrets) }}"

          echo "${{ toJson(secrets) }}" | jq -r '.[] | "\(.U041VQM5ZTK_AWS_PROFILE_NAME)"'

          secrets=${{ toJson(secrets) }}

          # echo "$secrets" | jq -r '.[] | "\(.U041VQM5ZTK_AWS_PROFILE_NAME)"' | while read name ; do
          #   echo "name: $name"
          # done

          echo "$secrets" | jq -r '.[] | "\(.U041VQM5ZTK_AWS_PROFILE_NAME)"'
        shell: bash
