name: Get github commit details
on:
  push:
    tags:
      - "v*"

jobs:
  get_github_details:
    runs-on: ubuntu-latest
    steps:
      - name: Echo env
        run: |
          echo "message: ${{ github.event.head_commit.message }}"
          echo "actor: ${{ github.actor }}"
          echo "sha: ${{ github.sha }}"
          echo "triggering_actor: ${{ github.triggering_actor }}"
          echo "actor_id: ${{ github.actor_id }}"
          echo "ref: ${{ github.ref }}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_WORKFLOW_SHA: ${GITHUB_WORKFLOW_SHA}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "Works. Tag is ${GITHUB_REF##*/}"
          echo "Works. Tag is ${GITHUB_REF}"
        shell: bash
      - name: "Curl and get tags"
        id: tag
        run: |
          tags=$(curl -i 'https://api.github.com/repos/jlieow/hello-github-api/git/refs/tags' \
          -H "Accept: application/json" \
          -H "Content-Type:application/json")

          echo $tags
        shell: bash
